package com.duyetdo.springmvc.model;
// Generated Mar 27, 2017 11:22:56 AM by Hibernate Tools 5.2.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Contract generated by hbm2java
 */
@Entity
@Table(name = "contract", catalog = "Project_1")
public class Contract implements java.io.Serializable {

	private String contractId;
	private Project project;
	private String name;
	private Date start;
	private Date end;

	public Contract() {
	}

	public Contract(String contractId) {
		this.contractId = contractId;
	}

	public Contract(String contractId, Project project, String name, Date start, Date end) {
		this.contractId = contractId;
		this.project = project;
		this.name = name;
		this.start = start;
		this.end = end;
	}

	@Id

	@Column(name = "contract_ID", unique = true, nullable = false, length = 45)
	public String getContractId() {
		return this.contractId;
	}

	public void setContractId(String contractId) {
		this.contractId = contractId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_project")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "start", length = 10)
	public Date getStart() {
		return this.start;
	}

	public void setStart(Date start) {
		this.start = start;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "end", length = 10)
	public Date getEnd() {
		return this.end;
	}

	public void setEnd(Date end) {
		this.end = end;
	}

}
