package com.duyetdo.springmvc.model;
// Generated Mar 27, 2017 11:22:56 AM by Hibernate Tools 5.2.0.CR1

import static javax.persistence.GenerationType.IDENTITY;

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.validation.constraints.Pattern;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotBlank;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", catalog = "Project_1")
public class Customer implements java.io.Serializable {
	
	private Integer id;

	@Pattern(regexp="^[a-zA-Z0-9_.-]*$")
	@NotBlank
	private String customerId;
	
	@NotBlank
	private String name;
	
	@Email
	@NotBlank
	private String email;
	
	@Pattern(regexp="^(\\(?\\+?[0-9]*\\)?)?[0-9_\\- \\(\\)]*$")
	@NotBlank
	private String phone;
	
	@Pattern(regexp="^(\\(?\\+?[0-9]*\\)?)?[0-9_\\- \\(\\)]*$")
	@NotBlank
	private String fax;
	
	@NotBlank
	private String address;
	
	private Set<Project> projects = new HashSet<Project>();

	public Customer() {
	}

	public Customer(String customerId) {
		this.customerId = customerId;
	}

	public Customer(String customerId, String name, String email, String phone, String fax, String address,
			Set<Project> projects) {
		this.customerId = customerId;
		this.name = name;
		this.email = email;
		this.phone = phone;
		this.fax = fax;
		this.address = address;
		this.projects = projects;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	
	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "customer_ID", unique = true, nullable = false, length = 45)
	public String getCustomerId() {
		return this.customerId;
	}

	public void setCustomerId(String customerId) {
		this.customerId = customerId;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "email", length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "phone", length = 45)
	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	@Column(name = "fax", length = 45)
	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "customer")
	public Set<Project> getProjects() {
		return this.projects;
	}

	public void setProjects(Set<Project> projects) {
		this.projects = projects;
	}

}
