package com.duyetdo.springmvc.model;
// Generated Mar 27, 2017 11:22:56 AM by Hibernate Tools 5.2.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;

import java.util.Date;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.validation.constraints.NotNull;

import org.hibernate.validator.constraints.NotBlank;
import org.springframework.format.annotation.DateTimeFormat;
import org.springframework.format.annotation.NumberFormat;
import org.springframework.format.annotation.NumberFormat.Style;

/**
 * Fee generated by hbm2java
 */
@Entity
@Table(name = "fee", catalog = "Project_1")
public class Fee implements java.io.Serializable {

	private Integer feeId;
	
	@NotNull
	private Project project;
	
	@NotBlank
	private String name;
	
	@NumberFormat(style = Style.CURRENCY, pattern = "###,###,###,###,###.############")
	@NotNull
	private Double value;
	
	@NotBlank
	private String currency;
	
	@NumberFormat(style = Style.CURRENCY, pattern = "###,###,###,###,###.############")
	@NotNull
	private Double rate;
	
	@DateTimeFormat(pattern = "dd-MM-yyyy")
	@NotNull
	private Date date;
	

	public Fee() {
	}

	public Fee(Project project, String name, Double value, String currency, Double rate, Date date) {
		this.project = project;
		this.name = name;
		this.value = value;
		this.currency = currency;
		this.rate = rate;
		this.date = date;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "fee_ID", unique = true, nullable = false)
	public Integer getFeeId() {
		return this.feeId;
	}

	public void setFeeId(Integer feeId) {
		this.feeId = feeId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "id_project")
	public Project getProject() {
		return this.project;
	}

	public void setProject(Project project) {
		this.project = project;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "value", precision = 22, scale = 0)
	public Double getValue() {
		return this.value;
	}

	public void setValue(Double value) {
		this.value = value;
	}

	@Column(name = "currency")
	public String getCurrency() {
		return currency;
	}

	public void setCurrency(String currency) {
		this.currency = currency;
	}

	@Column(name = "rate", precision = 22, scale = 0)
	public Double getRate() {
		return rate;
	}

	public void setRate(Double rate) {
		this.rate = rate;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date", length = 10)
	public Date getDate() {
		return date;
	}

	public void setDate(Date date) {
		this.date = date;
	}
		
}
